spring.application.name=jpa

spring.datasource.url= jdbc:postgresql://localhost:5432/${NAME_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${SENHA_DB}
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.jdbc.lab.non_contextual_creation = true
spring.jpa.show-sql=true

